
version: '3'

services:
    base: &base
      hostname: app
      image: backend-challenge
      stdin_open: true
      tty: true
      build:
        context: .
        dockerfile: Dockerfile
      volumes:
        - .:/home/python/app
      environment: &env
          ENV: "development"
          LOG_LEVEL: "debug"
          PYTHONPATH: "/home/python/app"
          JWT_ACCESS_TOKEN_EXPIRE_MINUTES: 30
          JWT_ALGORITHM: "HS256"
          JWT_SECRET_KEY: "some key"
          WEB_APP_DEBUG: "true"
          WEB_APP_DESCRIPTION: "App"
          WEB_APP_TITLE: "App"
          WEB_APP_VERSION: "0.0.1"
          WEB_SERVER_HOST: "0.0.0.0"
          WEB_SERVER_PORT: 8000
          WEB_SERVER_RELOAD: "true"

    app:
        <<: *base
        command: /bin/ash -c "poetry install && poetry run python manage.py runserver 0.0.0.0:8000"
        ports:
          - "8000:8000"
